config/routes.rb
# class RoleRouteConstraint
#   def initialize(&block)
#     @block = block || lambda { |user| true }
#   end

#   def matches?(request)
#     user = current_user(request)
#     user.present? && @block.call(user)
#   end

#   def current_user(request)
#     User.find_by_id(request.session[:user_id])
#   end
# end

  # class NewUserConstraint 
  #   def self.matches?(request) 
  #     request.query_parameters[user.role] == 'admin' 
  #   end 
  # end

Rails.application.routes.draw do
  resources :orders, :books, :authors, :genres, :users

  root to: "books#index"

  get "sessions", to: "sessions#sign"
  post "sessions", to: "sessions#enter"
  delete "sessions", to: "sessions#destroy"

  get "categories/genre/:genre", to: "categories#get_books_genre"
  get "categories/search/", to: "categories#get_books_search"

  get "shoping/:id", to: "shopings#index"
  post "shoping", to: "shopings#new"
  get "shoping", to: "shopings#show"
  post "shoping/finish/:id", to: "shopings#finish"
  delete "shoping", to: "shopings#destroy"

  # get "/books/new", to: "books#new", constraints: { Current.user.present? && Current.user.role == "admin" }


  # authenticate :user, -> (u) { u.role.admin.present? } do
  #   get "/books/new", to: "books#new"
  # end


  # constraints RoleRouteConstraint.new { |user| user.has_role? :admin } do
  #   get "/books/new", to: "books#new"
  # end
  
  

end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    has_many :orders, dependent: :destroy_async

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true, format: {with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/}
    validates :password, presence: true, format: {with: /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}\z/}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :first_surname, :second_surname, :email, :password, :telephone, :address, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_with(model: user) do |form|
  - if user.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.each do |error|
          %li= error.full_message
  %div.form-group.field.w-25
    = form.label :name, "Nombre", style: "display: block", required: true
    = form.text_field :name, class: "form-control"
  %div.form-group.field.w-25
    = form.label :first_surname, "Primer apellido", style: "display: block", required: true
    = form.text_field :first_surname, class: "form-control"
  %div.form-group.field.w-25
    = form.label :second_surname, "Segundo apellido", style: "display: block"
    = form.text_field :second_surname, class: "form-control"
  %div.form-group.field.w-25
    = form.label :email, "Email", style: "display: block", required: true
    = form.text_field :email, class: "form-control"
  %div.form-group.field.w-25
    = form.label :password, "Contraseña", style: "display: block", required: true
    = form.password_field :password, class: "form-control"
  %div.form-group.field.w-25
    = form.label :password_confirmation, "Confirmar contraseña", style: "display: block", required: true
    = form.password_field :password_confirmation, class: "form-control"
  %div.form-group.field.w-25
    = form.label :telephone, "Teléfono", style: "display: block", required: true
    = form.number_field :telephone, class: "form-control"
  %div.form-group.field.w-25
    = form.label :address, "Dirección", style: "display: block", required: true
    = form.text_field :address, class: "form-control"
  - if Current.user.present? && Current.user.role == "admin"
    %div.form-group.field.w-25
      = form.label :role, style: "display: block", required: true
      = form.text_field :role, class: "form-control"
  %div
    = form.submit :Registrar, class: 'btn btn-primary'

app/views/users/_user.html.haml
%div{:id => "#{dom_id user}"}
  %p
    %strong Nombre:
    = user.name
  %p
    %strong Primer apellido:
    = user.first_surname
  %p
    %strong Segundo apellido:
    = user.second_surname
  %p
    %strong Email:
    = user.email
  -# %p
  -#   %strong Contraseña:
  -#   = user.password
  %p
    %strong Teléfono:
    = user.telephone
  %p
    %strong Dirección:
    = user.address
  - if Current.user.present? && Current.user.role == "admin"
    %p
      %strong Role:
      = user.role

app/views/users/edit.html.haml
%h1 Editar perfil
= render "form", user: @user
%br/
%div
  = link_to "Ver perfil", @user

app/views/users/index.html.haml
%h1 Usuarios
#users
  - @users.each do |user|
    = render user
    %p
      = link_to "Ver perfil", user
= link_to "Crear usuario", new_user_path

app/views/users/new.html.haml
%h1 Nuevo usuario
= render "form", user: @user
%br/
- if Current.user.present? && Current.user.role == "admin"
  %div
    = link_to "Volver a usuarios", users_path

app/views/users/show.html.haml
= render @user
- if Current.user.present?
  %div
    = link_to "Editar perfil", edit_user_path(@user)
    |
    = link_to "Ver pedidos", shoping_path
    |
    = button_to "Eliminar cuenta", @user, method: :delete, class: "btn btn-link" 
    - if Current.user.present? && Current.user.role == "admin"
      |
      = link_to "Ir a usuarios", users_path