config/routes.rb
# class RoleRouteConstraint
#   def initialize(&block)
#     @block = block || lambda { |user| true }
#   end

#   def matches?(request)
#     user = current_user(request)
#     user.present? && @block.call(user)
#   end

#   def current_user(request)
#     User.find_by_id(request.session[:user_id])
#   end
# end

  # class NewUserConstraint 
  #   def self.matches?(request) 
  #     request.query_parameters[user.role] == 'admin' 
  #   end 
  # end

Rails.application.routes.draw do
  resources :orders, :books, :authors, :genres, :users

  root to: "books#index"

  get "sessions", to: "sessions#sign"
  post "sessions", to: "sessions#enter"
  delete "sessions", to: "sessions#destroy"

  get "categories/genre/:genre", to: "categories#get_books_genre"
  get "categories/search/", to: "categories#get_books_search"

  get "shoping/:id", to: "shopings#index"
  post "shoping", to: "shopings#new"
  get "shoping", to: "shopings#show"
  post "shoping/finish/:id", to: "shopings#finish"
  delete "shoping", to: "shopings#destroy"

  # get "/books/new", to: "books#new", constraints: { Current.user.present? && Current.user.role == "admin" }


  # authenticate :user, -> (u) { u.role.admin.present? } do
  #   get "/books/new", to: "books#new"
  # end


  # constraints RoleRouteConstraint.new { |user| user.has_role? :admin } do
  #   get "/books/new", to: "books#new"
  # end
  
  

end

app/views/shared/_flash.html.haml
- if flash[:notice]
  .alert.alert-info.mt-4{:role => "alert"}
    = flash[:notice]
- if flash[:alert]
  .alert.alert-warning.mt-4{:role => "alert"}
    = flash[:alert]

-# %p{:style => "color: green"}= notice

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => "/"} Home
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        %a.nav-link{:href => "/"} Libros
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"} Géneros
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          - @genres.each do |genre|
            = link_to genre.definition, {:controller => "categories", :action => "get_books_genre", :genre => genre.id }, class: "dropdown-item"
      %li.nav-item
        = search_form_for(@query, url: "/categories/search", method: :get, class: 'form-inline my-2 my-lg-0') do |f|
          = f.search_field :title_or_author_name_or_synopsis_cont, placeholder: "Título, autor o descripción", class: 'form-control mr-sm-2'
          = f.submit "Buscar", class: 'btn btn-primary my-2 my-sm-0'
      - if Current.user.present? && Current.user.role == "admin"
        = link_to "Crear nuevo libro", new_book_path, class: "btn btn-link my-2 my-lg-0"
        = link_to "Administrar autores", authors_path, class: "btn btn-link my-2 my-lg-0"
        = link_to "Administrar géneros", genres_path, class: "btn btn-link my-2 my-lg-0"
        = link_to "Administrar usuarios", users_path, class: "btn btn-link my-2 my-lg-0"
        = link_to "Administrar pedidos", orders_path, class: "btn btn-link my-2 my-lg-0"
  %ul.navbar-nav.ms-auto.mb-2.mb-lg-0
    - if Current.user
      %li.nav-item
        = link_to Current.user.email, {:controller => "users", :action => "show", :id => Current.user.id }, class: "btn btn-link my-2 my-lg-0"
      %li.nav-item
        = button_to "Salir", sessions_path, method: :delete, class: "btn btn-outline-primary my-2 my-lg-0"
    - else
      %li.nav-item
        = button_to "Registrarse", new_user_path, method: :get, class: "btn btn-link my-2 my-lg-0"
      %li.nav-item
        = button_to "Entrar", sessions_path, method: :get, class: "btn btn-outline-primary my-2 my-lg-0"

app/views/shared/_pagination.html.haml
.pag-bar.mt-5.pt-5
  != pagy_bootstrap_nav(@pagy)