config/routes.rb
# class RoleRouteConstraint
#   def initialize(&block)
#     @block = block || lambda { |user| true }
#   end

#   def matches?(request)
#     user = current_user(request)
#     user.present? && @block.call(user)
#   end

#   def current_user(request)
#     User.find_by_id(request.session[:user_id])
#   end
# end

  # class NewUserConstraint 
  #   def self.matches?(request) 
  #     request.query_parameters[user.role] == 'admin' 
  #   end 
  # end

Rails.application.routes.draw do
  resources :orders, :books, :authors, :genres, :users

  root to: "books#index"

  get "sessions", to: "sessions#sign"
  post "sessions", to: "sessions#enter"
  delete "sessions", to: "sessions#destroy"

  get "categories/genre/:genre", to: "categories#get_books_genre"
  get "categories/search/", to: "categories#get_books_search"

  get "shoping/:id", to: "shopings#index"
  post "shoping", to: "shopings#new"
  get "shoping", to: "shopings#show"
  post "shoping/finish/:id", to: "shopings#finish"
  delete "shoping", to: "shopings#destroy"

  # get "/books/new", to: "books#new", constraints: { Current.user.present? && Current.user.role == "admin" }


  # authenticate :user, -> (u) { u.role.admin.present? } do
  #   get "/books/new", to: "books#new"
  # end


  # constraints RoleRouteConstraint.new { |user| user.has_role? :admin } do
  #   get "/books/new", to: "books#new"
  # end
  
  

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :books
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:user_id, :state)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_with(model: order) do |form|
  - if order.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(order.errors.count, "error")
        prohibited this order from being saved:
      %ul
        - order.errors.each do |error|
          %li= error.full_message
  %div.form-group.field.w-25
    = form.label :user_id, "ID de usuario", style: "display: block", required: true
    = form.text_field :user_id, class: "form-control"
  %div.form-group.field.w-25
    = form.label :state, "Estado", style: "display: block", required: true
    = form.text_field :state, class: "form-control"
  %div
    = form.submit :Guardar, class: 'btn btn-primary'

app/views/orders/_order.html.haml
%div{:id => "#{dom_id order}"}
  - if Current.user.present? && Current.user.role == "admin"
    %p
      %strong Usuario:
      = order.user_id
    %p
      %strong Estado:
      = order.state
  %p
    %strong Libros: 
    - order.books.each do |book|
      = "- #{book.title}, #{book.price}€"
      - if order.state == "activo"
        = button_to "Eliminar", shoping_path(:order_id => order, :book_id => book), method: :delete, class: "btn btn-link my-2 my-lg-0 d-inline" 
      %br/
    - if order.state == "finalizado"
      %p
        %strong Fecha de compra: 
        =order.updated_at.strftime("%m/%d/%Y")
  %p
    %strong Importe: 
    - @totalsum = order.books.map { |book| book.price }.sum
    = "#{@totalsum}€"
  - if order.state == "activo"
    = button_to "Finalizar pedido", {:controller => "shopings", :action => "finish", :id => order.id }

app/views/orders/edit.html.haml
%h1 Editar pedido
= render "form", order: @order
%br/
%div
  = link_to "Ver pedido", @order
  |
  = link_to "Seguir comprando", books_path
  - if Current.user.present? && Current.user.role == "admin"
    %br/
    %div
      = link_to "Registro de pedidos", orders_path

app/views/orders/index.html.haml
%h1 Pedidos
= link_to "Seguir comprando", books_path
|
= link_to "Nuevo pedido", new_order_path
#orders
  - @orders.each do |order|
    = render order
    %p
      = link_to "Ver pedido", order

app/views/orders/new.html.haml
%h1 Nuevo pedido
= render "form", order: @order
%br/
%div
  = link_to "Ver pedidos", orders_path

app/views/orders/show.html.haml
= render @order
%div
  = link_to "Seguir comprando", books_path
  - if Current.user.present? && Current.user.role == "client"
    |
    = link_to "Ver pedidos", shoping_path
  - if Current.user.present? && Current.user.role == "admin"
    |
    %br/
    %div
      = link_to "Registro de pedidos", orders_path
      |
      = link_to "Editar pedido", edit_order_path(@order)  
      = button_to "Eliminar pedido", @order, method: :delete